CATEGORY_SUMMARIES = {
    "inventario": "productos stock categorias alertas inventario",
    "ventas": "ventas carrito facturacion transacciones historial",
    "clientes": "clientes compras contacto datos",
    "analytics": "estadisticas metricas vendidos negocio",
    "admin": "administracion usuarios permisos sistema",
    "auth": "autenticacion login logout tokens",
    "tienda": "tienda negocio horarios metodos pago",
    "licencia": "licencia activacion renovacion limites",
    "lealtad": "puntos recompensas frecuente",
    "seguridad": "auditoria logs bloqueos acceso",
    "websocket": "tiempo real notificaciones sincronizacion",
    "settings": "configuracion preferencias tema idioma",
    "validacion": "validacion importacion datos sanitizacion",
    "ia_assistant": "asistente conversacion contexto herramientas",
    "general": "salud sistema api utilidades",
}