# -*- coding: utf-8 -*-
TRANSLATIONS = {
    "es": {"nav.dashboard":"Dashboard","nav.ventas":"Ventas","nav.productos":"Productos","nav.clientes":"Clientes","nav.informes":"Informes","nav.configuracion":"Configuracion","nav.caja":"Caja","nav.inventario":"Inventario","nav.proveedores":"Proveedores","nav.nueva_venta":"Nueva Venta","nav.historial":"Historial","nav.categorias":"Categorias","nav.ajustes":"Ajustes","nav.resumen":"Resumen Diario","nav.exportar":"Exportar Datos","msg.exito":"Operacion exitosa","msg.error":"Error en la operacion","msg.guardar":"Guardar","msg.cancelar":"Cancelar","msg.eliminar":"Eliminar","msg.editar":"Editar","msg.buscar":"Buscar...","ventas.total":"Total","ventas.subtotal":"Subtotal","ventas.iva":"IVA","ventas.descuento":"Descuento","ventas.efectivo":"Efectivo","ventas.tarjeta":"Tarjeta","ventas.transferencia":"Transferencia","bio.autenticando":"Autenticando...","bio.fallo":"Autenticacion fallida","bio.exito":"Autenticacion exitosa","bio.requerida":"Autenticacion biometrica requerida"},
    "en": {"nav.dashboard":"Dashboard","nav.ventas":"Sales","nav.productos":"Products","nav.clientes":"Customers","nav.informes":"Reports","nav.configuracion":"Settings","nav.caja":"Cash Register","nav.inventario":"Inventory","nav.proveedores":"Suppliers","nav.nueva_venta":"New Sale","nav.historial":"History","nav.categorias":"Categories","nav.ajustes":"Adjustments","nav.resumen":"Daily Summary","nav.exportar":"Export Data","msg.exito":"Operation successful","msg.error":"Operation failed","msg.guardar":"Save","msg.cancelar":"Cancel","msg.eliminar":"Delete","msg.editar":"Edit","msg.buscar":"Search...","ventas.total":"Total","ventas.subtotal":"Subtotal","ventas.iva":"Tax","ventas.descuento":"Discount","ventas.efectivo":"Cash","ventas.tarjeta":"Card","ventas.transferencia":"Transfer","bio.autenticando":"Authenticating...","bio.fallo":"Authentication failed","bio.exito":"Authentication successful","bio.requerida":"Biometric authentication required"},
    "pt": {"nav.dashboard":"Painel","nav.ventas":"Vendas","nav.productos":"Produtos","nav.clientes":"Clientes","nav.informes":"Relatorios","nav.configuracion":"Configuracoes","nav.caja":"Caixa","nav.inventario":"Estoque","nav.proveedores":"Fornecedores","nav.nueva_venta":"Nova Venda","nav.historial":"Historico","nav.categorias":"Categorias","nav.ajustes":"Ajustes","nav.resumen":"Resumo Diario","nav.exportar":"Exportar Dados","msg.exito":"Operacao realizada","msg.error":"Erro na operacao","msg.guardar":"Salvar","msg.cancelar":"Cancelar","msg.eliminar":"Excluir","msg.editar":"Editar","msg.buscar":"Buscar...","ventas.total":"Total","ventas.subtotal":"Subtotal","ventas.iva":"Imposto","ventas.descuento":"Desconto","ventas.efectivo":"Dinheiro","ventas.tarjeta":"Cartao","ventas.transferencia":"Transferencia","bio.autenticando":"Autenticando...","bio.fallo":"Autenticacao falhou","bio.exito":"Autenticacao bem-sucedida","bio.requerida":"Autenticacao biometrica necessaria"},
}
def t(key, lang="es"):
    return TRANSLATIONS.get(lang, TRANSLATIONS.get("es", {})).get(key, key)
def available_languages():
    return list(TRANSLATIONS.keys())
