"""
tool_registry.py — Catalogo COMPLETO de herramientas para la IA Agéntica.
Registra las 144 rutas API del TPV como "tools" con descripcion,
parametros y tipo de acceso. El reasoning_engine consulta este
catalogo para decidir que herramienta usar.

Industrialization v5 — Agentic AI Layer (147 herramientas)
"""
from __future__ import annotations
from typing import Dict, Any, List, Optional
from dataclasses import dataclass


@dataclass
class ToolDefinition:
    """Definicion de una herramienta disponible para el agente."""
    name: str
    description: str
    category: str
    route: str
    method: str
    params: List[Dict[str, str]]
    requires_auth: bool = True
    requires_role: Optional[str] = None


def _t(name, desc, cat, route, method, params, role=None, auth=True):
    """Helper rapido para crear ToolDefinition."""
    return ToolDefinition(name, desc, cat, route, method, params, auth, role)


TOOL_CATALOG: Dict[str, ToolDefinition] = {
    # ══════════════════════════════════════════
    #  ADMIN (admin_bp) — 11 herramientas
    # ══════════════════════════════════════════
    "listar_usuarios": _t("listar_usuarios",
        "Lista todos los usuarios del sistema con sus roles y estado",
        "admin", "/api/usuarios", "GET",
        [{"name": "rol", "type": "str", "description": "Filtrar por rol", "required": False}],
        role="administrador"),
    "crear_usuario": _t("crear_usuario",
        "Crea un nuevo usuario con nombre, username, password y rol",
        "admin", "/api/usuarios/crear", "POST",
        [{"name": "username", "type": "str", "description": "Nombre de usuario", "required": True},
         {"name": "nombre", "type": "str", "description": "Nombre completo", "required": True},
         {"name": "password", "type": "str", "description": "Contrasena", "required": True},
         {"name": "rol", "type": "str", "description": "administrador, vendedor, desarrollador", "required": True}],
        role="administrador"),
    "desactivar_usuario": _t("desactivar_usuario",
        "Desactiva un usuario del sistema",
        "admin", "/api/usuarios/<usuario_id>", "DELETE",
        [{"name": "usuario_id", "type": "str", "description": "ID del usuario", "required": True}],
        role="administrador"),
    "reset_password": _t("reset_password",
        "Resetea la contrasena de un usuario",
        "admin", "/api/usuarios/<usuario_id>/reset-password", "POST",
        [{"name": "usuario_id", "type": "str", "description": "ID del usuario", "required": True},
         {"name": "nueva_password", "type": "str", "description": "Nueva contrasena", "required": True}],
        role="administrador"),
    "listar_licencias": _t("listar_licencias",
        "Lista todas las licencias del sistema",
        "admin", "/api/licencias", "GET", [],
        role="administrador"),
    "crear_licencia": _t("crear_licencia",
        "Crea una nueva licencia para un dispositivo",
        "admin", "/api/licencias/crear", "POST",
        [{"name": "device_id", "type": "str", "description": "ID del dispositivo", "required": True},
         {"name": "tipo", "type": "str", "description": "Tipo de licencia", "required": True}],
        role="desarrollador"),
    "verificar_licencia": _t("verificar_licencia",
        "Verifica el estado de una licencia de un administrador",
        "admin", "/api/licencias/verificar/<admin_id>", "GET",
        [{"name": "admin_id", "type": "str", "description": "ID del admin", "required": True}],
        role="administrador"),
    "desactivar_licencia": _t("desactivar_licencia",
        "Desactiva una licencia",
        "admin", "/api/licencias/<licencia_id>", "DELETE",
        [{"name": "licencia_id", "type": "str", "description": "ID de licencia", "required": True}],
        role="desarrollador"),
    "get_privilegios": _t("get_privilegios",
        "Obtiene los privilegios de un rol especifico",
        "admin", "/api/privilegios/<rol>", "GET",
        [{"name": "rol", "type": "str", "description": "Nombre del rol", "required": True}],
        role="administrador"),
    "set_privilegios": _t("set_privilegios",
        "Establece los privilegios de un rol",
        "admin", "/api/privilegios/<rol>", "PUT",
        [{"name": "rol", "type": "str", "description": "Nombre del rol", "required": True},
         {"name": "privilegios", "type": "list", "description": "Lista de privilegios", "required": True}],
        role="desarrollador"),
    "reset_privilegios": _t("reset_privilegios",
        "Restablece los privilegios de un rol a los valores por defecto",
        "admin", "/api/privilegios/<rol>/restablecer", "POST",
        [{"name": "rol", "type": "str", "description": "Nombre del rol", "required": True}],
        role="desarrollador"),

    # ══════════════════════════════════════════
    #  AI / ANALYTICS (ai_bp) — 12 herramientas
    # ══════════════════════════════════════════
    "dashboard_general": _t("dashboard_general",
        "Dashboard general con KPIs y resumen del negocio",
        "analytics", "/dashboard", "GET",
        [{"name": "dias", "type": "int", "description": "Periodo en dias", "required": False}]),
    "analytics_abc": _t("analytics_abc",
        "Analisis ABC de productos: clasifica por contribucion a ingresos",
        "analytics", "/analytics/abc", "GET", []),
    "analytics_cross_selling": _t("analytics_cross_selling",
        "Analisis de cross-selling: productos que se venden juntos",
        "analytics", "/analytics/cross-selling", "GET", []),
    "analytics_prices": _t("analytics_prices",
        "Analisis de precios: comparativa y optimizacion de precios",
        "analytics", "/analytics/prices", "GET", []),
    "analytics_kpis": _t("analytics_kpis",
        "KPIs del negocio: ventas, clientes, ticket promedio, etc",
        "analytics", "/kpis", "GET",
        [{"name": "dias", "type": "int", "description": "Periodo en dias", "required": False}]),
    "predict_dashboard": _t("predict_dashboard",
        "Dashboard predictivo: tendencias y pronosticos",
        "analytics", "/predict/dashboard", "GET", []),
    "predictor": _t("predictor",
        "Motor predictivo: pronostico de ventas y demanda",
        "analytics", "/predictor", "GET",
        [{"name": "dias", "type": "int", "description": "Dias a pronosticar", "required": False}]),
    "fraud_dashboard": _t("fraud_dashboard",
        "Dashboard de deteccion de fraude y anomalias",
        "analytics", "/fraud/dashboard", "GET", []),
    "fraud": _t("fraud",
        "Analisis de fraude y transacciones sospechosas",
        "analytics", "/fraud", "GET", []),
    "prices": _t("prices",
        "Gestion y analisis de precios de productos",
        "analytics", "/prices", "GET", []),
    "analytics_combined": _t("analytics_combined",
        "Endpoint combinado de analytics para compatibilidad",
        "analytics", "/analytics", "GET", []),
    "alertas_analytics": _t("alertas_analytics",
        "Sistema de alertas basado en analytics",
        "analytics", "/alerts", "GET", []),

    # ══════════════════════════════════════════
    #  AUTH (auth_bp) — 5 herramientas
    # ══════════════════════════════════════════
    "login": _t("login",
        "Inicia sesion con username y password",
        "auth", "/api/auth/login", "POST",
        [{"name": "username", "type": "str", "description": "Usuario", "required": True},
         {"name": "password", "type": "str", "description": "Contrasena", "required": True}],
        auth=False),
    "logout": _t("logout",
        "Cierra la sesion actual del usuario",
        "auth", "/api/auth/logout", "POST", []),
    "auth_me": _t("auth_me",
        "Obtiene informacion del usuario autenticado actual",
        "auth", "/api/auth/me", "GET", []),
    "cambiar_password": _t("cambiar_password",
        "Cambia la contrasena del usuario actual",
        "auth", "/api/auth/cambiar-password", "POST",
        [{"name": "password_actual", "type": "str", "description": "Contrasena actual", "required": True},
         {"name": "password_nueva", "type": "str", "description": "Nueva contrasena", "required": True}]),
    "auto_backup": _t("auto_backup",
        "Guarda backup automatico y sincroniza con Supabase si esta disponible",
        "auth", "/api/auth/auto-backup", "POST", []),

    # ══════════════════════════════════════════
    #  INVENTARIO (inv_bp) — 18 herramientas
    # ══════════════════════════════════════════
    "get_catalogo": _t("get_catalogo",
        "Obtiene el catalogo completo de productos con precios y categorias",
        "inventario", "/api/catalogo", "GET",
        [{"name": "categoria", "type": "str", "description": "Filtrar por categoria", "required": False}]),
    "inventario_general": _t("inventario_general",
        "Obtiene el inventario general consolidado con stock actual",
        "inventario", "/api/inventario/general", "GET",
        [{"name": "categoria", "type": "str", "description": "Filtrar por categoria", "required": False}]),
    "entrada_producto": _t("entrada_producto",
        "Registra una entrada de mercancia a un producto",
        "inventario", "/api/inventario/entrada", "POST",
        [{"name": "producto_id", "type": "str", "description": "ID del producto", "required": True},
         {"name": "cantidad", "type": "float", "description": "Cantidad entrante", "required": True},
         {"name": "costo", "type": "float", "description": "Costo unitario", "required": False},
         {"name": "motivo", "type": "str", "description": "Motivo de la entrada", "required": False}],
        role="vendedor"),
    "stock_masivo": _t("stock_masivo",
        "Actualiza stock de multiples productos en una sola operacion",
        "inventario", "/api/stock/masivo", "POST",
        [{"name": "productos", "type": "list", "description": "Lista de {producto_id, cantidad}", "required": True}],
        role="vendedor"),
    "importar_validado": _t("importar_validado",
        "Importacion profesional con validacion dry-run + transaccion atomica",
        "inventario", "/api/importar-validado", "POST",
        [{"name": "productos", "type": "list", "description": "Lista de productos a importar", "required": True},
         {"name": "ejecutar", "type": "bool", "description": "True para ejecutar, False solo valida", "required": False}],
        role="vendedor"),
    "importar_catalogo": _t("importar_catalogo",
        "Importa catalogo de productos desde datos externos",
        "inventario", "/api/inventario/importar-catalogo", "POST",
        [{"name": "productos", "type": "list", "description": "Lista de productos", "required": True}],
        role="vendedor"),
    "sync_catalogo": _t("sync_catalogo",
        "Sincroniza el catalogo desde el frontend al backend",
        "inventario", "/api/catalogo/sync", "POST",
        [{"name": "productos", "type": "list", "description": "Lista de productos", "required": True}],
        role="vendedor"),
    "sync_desde_inventario": _t("sync_desde_inventario",
        "Sincroniza productos desde inventario general al catalogo",
        "inventario", "/api/catalogo/sync-desde-inventario", "POST", [],
        role="administrador"),
    "sincronizar_completo": _t("sincronizar_completo",
        "Sincronizacion completa de todas las tablas",
        "inventario", "/api/sincronizar-completo", "POST", [],
        role="administrador"),
    "eliminar_inventario_general": _t("eliminar_inventario_general",
        "Elimina un producto del inventario general",
        "inventario", "/api/inventario/general/eliminar", "POST",
        [{"name": "producto_id", "type": "str", "description": "ID del producto", "required": True}],
        role="administrador"),
    "limpiar_tablas": _t("limpiar_tablas",
        "Limpia todas las tablas del sistema (operacion destructiva)",
        "inventario", "/api/limpiar-tablas", "POST", [],
        role="desarrollador"),
    "inventario_diario": _t("inventario_diario",
        "Obtiene el inventario diario asignado a un vendedor",
        "inventario", "/api/inventario/diario/<vendedor_id>", "GET",
        [{"name": "vendedor_id", "type": "str", "description": "ID del vendedor", "required": True}]),
    "asignar_inventario": _t("asignar_inventario",
        "Asigna inventario diario a un vendedor",
        "inventario", "/api/inventario/asignar-diario", "POST",
        [{"name": "vendedor_id", "type": "str", "description": "ID del vendedor", "required": True},
         {"name": "productos", "type": "list", "description": "Lista de productos con cantidades", "required": True}],
        role="administrador"),
    "conteo_vendedor": _t("conteo_vendedor",
        "Registra conteo de inventario realizado por el vendedor",
        "inventario", "/api/inventario/diario/conteo", "POST",
        [{"name": "vendedor_id", "type": "str", "description": "ID del vendedor", "required": True},
         {"name": "conteo", "type": "list", "description": "Lista de {producto_id, cantidad}", "required": True}],
        role="vendedor"),
    "cierre_vendedor": _t("cierre_vendedor",
        "Cierra el inventario diario de un vendedor",
        "inventario", "/api/inventario/diario/cierre", "POST",
        [{"name": "vendedor_id", "type": "str", "description": "ID del vendedor", "required": True}],
        role="vendedor"),
    "historial_entradas": _t("historial_entradas",
        "Historial de entradas de mercancia",
        "inventario", "/api/inventario/entradas", "GET",
        [{"name": "dias", "type": "int", "description": "Dias a consultar", "required": False}]),
    "historial_cierres": _t("historial_cierres",
        "Historial de cierres de inventario de un vendedor",
        "inventario", "/api/inventario/diario/historial/<vendedor_id>", "GET",
        [{"name": "vendedor_id", "type": "str", "description": "ID del vendedor", "required": True}]),
    "cierre_admin": _t("cierre_admin",
        "Cierre administrativo de inventario",
        "inventario", "/api/inventario/cierre-admin", "POST", [],
        role="administrador"),

    # ══════════════════════════════════════════
    #  VENTAS (ventas_bp) — 11 herramientas
    # ══════════════════════════════════════════
    "reporte_ventas": _t("reporte_ventas",
        "Reporte de ventas con filtros por fecha, metodo y estado",
        "ventas", "/api/reportes/ventas", "GET",
        [{"name": "fecha_inicio", "type": "str", "description": "Fecha inicio YYYY-MM-DD", "required": False},
         {"name": "fecha_fin", "type": "str", "description": "Fecha fin YYYY-MM-DD", "required": False},
         {"name": "metodo_pago", "type": "str", "description": "Filtrar por metodo de pago", "required": False}]),
    "resumen": _t("resumen",
        "Resumen general del negocio: ventas, gastos, ganancias",
        "ventas", "/api/reportes/resumen", "GET",
        [{"name": "dias", "type": "int", "description": "Periodo en dias", "required": False}]),
    "ganancias": _t("ganancias",
        "Reporte de ganancias detallado por periodo",
        "ventas", "/api/reportes/ganancias", "GET",
        [{"name": "fecha_inicio", "type": "str", "description": "Fecha inicio", "required": False},
         {"name": "fecha_fin", "type": "str", "description": "Fecha fin", "required": False}]),
    "historial_diario": _t("historial_diario",
        "Historial de ventas por dia",
        "ventas", "/api/historial/diario", "GET",
        [{"name": "dias", "type": "int", "description": "Dias a consultar", "required": False}]),
    "historial_detalle": _t("historial_detalle",
        "Detalle de ventas de una fecha especifica",
        "ventas", "/api/historial/diario/<fecha>", "GET",
        [{"name": "fecha", "type": "str", "description": "Fecha YYYY-MM-DD", "required": True}]),
    "listar_gastos": _t("listar_gastos",
        "Lista todos los gastos registrados",
        "ventas", "/api/gastos", "GET",
        [{"name": "fecha_inicio", "type": "str", "description": "Fecha inicio", "required": False},
         {"name": "fecha_fin", "type": "str", "description": "Fecha fin", "required": False}]),
    "crear_gasto": _t("crear_gasto",
        "Registra un nuevo gasto",
        "ventas", "/api/gastos", "POST",
        [{"name": "descripcion", "type": "str", "description": "Descripcion del gasto", "required": True},
         {"name": "monto", "type": "float", "description": "Monto del gasto", "required": True},
         {"name": "categoria", "type": "str", "description": "Categoria del gasto", "required": False}],
        role="vendedor"),
    "eliminar_gasto": _t("eliminar_gasto",
        "Elimina un gasto registrado",
        "ventas", "/api/gastos/<gasto_id>", "DELETE",
        [{"name": "gasto_id", "type": "str", "description": "ID del gasto", "required": True}],
        role="administrador"),
    "listar_descuentos": _t("listar_descuentos",
        "Lista todos los descuentos activos",
        "ventas", "/api/descuentos", "GET", []),
    "crear_descuento": _t("crear_descuento",
        "Crea un nuevo descuento",
        "ventas", "/api/descuentos", "POST",
        [{"name": "nombre", "type": "str", "description": "Nombre del descuento", "required": True},
         {"name": "porcentaje", "type": "float", "description": "Porcentaje de descuento", "required": True},
         {"name": "activo", "type": "bool", "description": "Si esta activo", "required": False}],
        role="administrador"),
    "eliminar_descuento": _t("eliminar_descuento",
        "Elimina un descuento",
        "ventas", "/api/descuentos/<int:did>", "DELETE",
        [{"name": "did", "type": "int", "description": "ID del descuento", "required": True}],
        role="administrador"),

    # ══════════════════════════════════════════
    #  TIENDA ONLINE (tienda_bp) — 12 herramientas
    # ══════════════════════════════════════════
    "listar_productos_tienda": _t("listar_productos_tienda",
        "Lista productos disponibles en la tienda online",
        "tienda", "/api/productos", "GET",
        [{"name": "categoria", "type": "str", "description": "Filtrar por categoria", "required": False}]),
    "producto_detalle": _t("producto_detalle",
        "Obtiene detalle completo de un producto",
        "tienda", "/api/productos/<producto_id>", "GET",
        [{"name": "producto_id", "type": "str", "description": "ID del producto", "required": True}]),
    "subir_imagen_producto": _t("subir_imagen_producto",
        "Sube o actualiza la imagen de un producto (base64)",
        "tienda", "/api/productos/<producto_id>/imagen", "POST",
        [{"name": "producto_id", "type": "str", "description": "ID del producto", "required": True}],
        role="vendedor"),
    "generar_qr_productos": _t("generar_qr_productos",
        "Genera codigos QR para hasta 40 productos",
        "tienda", "/api/productos/qr", "GET", [],
        role="vendedor"),
    "listar_clientes": _t("listar_clientes",
        "Lista todos los clientes registrados",
        "tienda", "/api/clientes", "GET",
        [{"name": "buscar", "type": "str", "description": "Termino de busqueda", "required": False}]),
    "perfil_cliente": _t("perfil_cliente",
        "Perfil publico de un cliente",
        "tienda", "/api/clientes/<cliente_id>", "GET",
        [{"name": "cliente_id", "type": "str", "description": "ID del cliente", "required": True}]),
    "login_cliente": _t("login_cliente",
        "Inicio de sesion para clientes de la tienda",
        "tienda", "/api/clientes/login", "POST",
        [{"name": "email", "type": "str", "description": "Email del cliente", "required": True},
         {"name": "password", "type": "str", "description": "Contrasena", "required": True}],
        auth=False),
    "registrar_cliente": _t("registrar_cliente",
        "Registra un nuevo cliente en la tienda",
        "tienda", "/api/clientes/registrar", "POST",
        [{"name": "nombre", "type": "str", "description": "Nombre", "required": True},
         {"name": "email", "type": "str", "description": "Email", "required": True},
         {"name": "password", "type": "str", "description": "Contrasena", "required": True}],
        auth=False),
    "crear_pedido": _t("crear_pedido",
        "Crea un nuevo pedido en la tienda online",
        "tienda", "/api/pedidos", "POST",
        [{"name": "cliente_id", "type": "str", "description": "ID del cliente", "required": True},
         {"name": "productos", "type": "list", "description": "Lista de items del pedido", "required": True}],
        auth=False),
    "obtener_pedido": _t("obtener_pedido",
        "Obtiene detalle de un pedido especifico",
        "tienda", "/api/pedidos/<pedido_id>", "GET",
        [{"name": "pedido_id", "type": "str", "description": "ID del pedido", "required": True}]),
    "actualizar_estado_pedido": _t("actualizar_estado_pedido",
        "Actualiza el estado de un pedido",
        "tienda", "/api/pedidos/<pedido_id>/estado", "POST",
        [{"name": "pedido_id", "type": "str", "description": "ID del pedido", "required": True},
         {"name": "estado", "type": "str", "description": "Nuevo estado", "required": True}],
        role="vendedor"),
    "resumen_pedidos": _t("resumen_pedidos",
        "Resumen de todos los pedidos de la tienda",
        "tienda", "/api/pedidos/resumen", "GET", []),
    "listar_tiendas": _t("listar_tiendas",
        "Lista todas las tiendas registradas",
        "tienda", "/api/tiendas", "GET", []),
    "eliminar_tienda": _t("eliminar_tienda",
        "Elimina o actualiza una tienda",
        "tienda", "/api/tiendas/<tienda_id>", "DELETE",
        [{"name": "tienda_id", "type": "str", "description": "ID de la tienda", "required": True}],
        role="administrador"),

    # ══════════════════════════════════════════
    #  LICENCIA (lic_bp) — 6 herramientas
    # ══════════════════════════════════════════
    "lic_validate": _t("lic_validate",
        "Verifica el estado de la licencia del dispositivo actual",
        "licencia", "/validate", "GET", [], auth=False),
    "lic_activate": _t("lic_activate",
        "Activa una licencia con una clave proporcionada",
        "licencia", "/activate", "POST",
        [{"name": "clave", "type": "str", "description": "Clave de activacion", "required": True}]),
    "lic_deactivate": _t("lic_deactivate",
        "Desactiva la licencia actual (solo desarrollador)",
        "licencia", "/deactivate", "POST", [], role="desarrollador"),
    "lic_generate": _t("lic_generate",
        "Genera una nueva licencia (solo desarrollador)",
        "licencia", "/generate", "POST",
        [{"name": "tipo", "type": "str", "description": "Tipo de licencia", "required": False}],
        role="desarrollador"),
    "lic_list": _t("lic_list",
        "Lista todas las licencias (solo desarrollador)",
        "licencia", "/list", "GET", [], role="desarrollador"),
    "lic_device_id": _t("lic_device_id",
        "Devuelve el device_id generado para este dispositivo",
        "licencia", "/device-id", "GET", [], auth=False),

    # ══════════════════════════════════════════
    #  LEALTAD (loyalty_bp) — 8 herramientas
    # ══════════════════════════════════════════
    "loyalty_enroll": _t("loyalty_enroll",
        "Inscribe un cliente en el programa de lealtad",
        "lealtad", "/enroll", "POST",
        [{"name": "cliente_id", "type": "str", "description": "ID del cliente", "required": True}]),
    "loyalty_points": _t("loyalty_points",
        "Consulta los puntos de un cliente",
        "lealtad", "/points", "GET",
        [{"name": "cliente_id", "type": "str", "description": "ID del cliente", "required": True}]),
    "loyalty_add_points": _t("loyalty_add_points",
        "Agrega puntos a un cliente",
        "lealtad", "/points/add", "POST",
        [{"name": "cliente_id", "type": "str", "description": "ID del cliente", "required": True},
         {"name": "puntos", "type": "int", "description": "Puntos a agregar", "required": True}],
        role="vendedor"),
    "loyalty_redeem": _t("loyalty_redeem",
        "Canjea puntos de un cliente por una recompensa",
        "lealtad", "/points/redeem", "POST",
        [{"name": "cliente_id", "type": "str", "description": "ID del cliente", "required": True},
         {"name": "puntos", "type": "int", "description": "Puntos a canjear", "required": True}]),
    "loyalty_history": _t("loyalty_history",
        "Historial de movimientos de puntos de un cliente",
        "lealtad", "/history", "GET",
        [{"name": "cliente_id", "type": "str", "description": "ID del cliente", "required": True}]),
    "loyalty_leaderboard": _t("loyalty_leaderboard",
        "Ranking de clientes con mas puntos",
        "lealtad", "/leaderboard", "GET", []),
    "loyalty_headless_order": _t("loyalty_headless_order",
        "Crea un pedido sin interfaz (headless) con puntos",
        "lealtad", "/headless/order", "POST",
        [{"name": "cliente_id", "type": "str", "description": "ID del cliente", "required": True},
         {"name": "productos", "type": "list", "description": "Lista de productos", "required": True}]),

    # ══════════════════════════════════════════
    #  SEGURIDAD (sec_bp) — 7 herramientas
    # ══════════════════════════════════════════
    "pci_tokenize": _t("pci_tokenize",
        "Tokeniza datos de pago (cumplimiento PCI-DSS)",
        "seguridad", "/pci/tokenize", "POST",
        [{"name": "card_data", "type": "str", "description": "Datos de tarjeta", "required": True}]),
    "pci_mask": _t("pci_mask",
        "Enmascara datos sensibles de tarjeta",
        "seguridad", "/pci/mask", "POST",
        [{"name": "card_number", "type": "str", "description": "Numero de tarjeta", "required": True}]),
    "pci_audit": _t("pci_audit",
        "Auditoria de cumplimiento PCI-DSS",
        "seguridad", "/pci/audit", "GET", [],
        role="administrador"),
    "het_status": _t("het_status",
        "Estado del sistema de deteccion de amenazas (HET)",
        "seguridad", "/het/status", "GET", []),
    "het_alerts": _t("het_alerts",
        "Alertas de seguridad del sistema HET",
        "seguridad", "/het/alerts", "GET", []),
    "ws_status": _t("ws_status",
        "Estado del sistema WebSocket",
        "seguridad", "/ws/status", "GET", []),
    "omnichannel_status": _t("omnichannel_status",
        "Estado del sistema omnicanal",
        "seguridad", "/omnichannel/status", "GET", []),

    # ══════════════════════════════════════════
    #  WEBSOCKET (security_websocket.py) — 4 herramientas
    # ══════════════════════════════════════════
    "ws_events": _t("ws_events",
        "Eventos WebSocket para terminal ID especifico",
        "websocket", "/ws/events/<tid>", "GET",
        [{"name": "tid", "type": "str", "description": "Terminal ID", "required": True}]),
    "ws_list": _t("ws_list",
        "Lista terminales WebSocket conectadas",
        "websocket", "/ws/terminals", "GET", []),
    "ws_register": _t("ws_register",
        "Registra un terminal WebSocket",
        "websocket", "/ws/register", "POST",
        [{"name": "terminal_id", "type": "str", "description": "ID del terminal", "required": True}]),
    "ws_unregister": _t("ws_unregister",
        "Desregistra un terminal WebSocket",
        "websocket", "/ws/unregister", "POST",
        [{"name": "terminal_id", "type": "str", "description": "ID del terminal", "required": True}]),

    # ══════════════════════════════════════════
    #  SETTINGS (settings_bp) — 21 herramientas
    # ══════════════════════════════════════════
    "export_backup": _t("export_backup",
        "Exporta backup completo de la base de datos",
        "settings", "/api/backup", "GET", [],
        role="administrador"),
    "biometric_setup": _t("biometric_setup",
        "Configura la autenticacion biometrica",
        "settings", "/api/biometric/setup", "GET", []),
    "get_state": _t("get_state",
        "Obtiene el estado guardado de la aplicacion",
        "settings", "/api/state", "GET", []),
    "save_state": _t("save_state",
        "Guarda el estado de la aplicacion",
        "settings", "/api/state", "POST",
        [{"name": "state", "type": "dict", "description": "Estado a guardar", "required": True}]),
    "get_status": _t("get_status",
        "Estado general del sistema",
        "settings", "/api/status", "GET", [], auth=False),
    "api_ping": _t("api_ping",
        "Ping al servidor para verificar conectividad",
        "settings", "/api/ping", "GET", [], auth=False),
    "health_full": _t("health_full",
        "Health check completo del sistema",
        "settings", "/api/health/full", "GET", []),
    "debug_health": _t("debug_health",
        "Health check con informacion de debug",
        "settings", "/api/debug/health", "GET", [],
        role="desarrollador"),
    "payment_tokenize": _t("payment_tokenize",
        "Tokeniza datos de pago para transaccion segura",
        "settings", "/api/payment/tokenize", "GET",
        [{"name": "card_data", "type": "str", "description": "Datos de tarjeta", "required": True}]),
    "api_sse": _t("api_sse",
        "Server-Sent Events endpoint",
        "settings", "/api/sse", "GET", []),
    "branch_info": _t("branch_info",
        "Informacion de la sucursal actual",
        "settings", "/api/branch/info", "GET", []),
    "branch_filter": _t("branch_filter",
        "Filtro por sucursal",
        "settings", "/api/branch/filter", "GET",
        [{"name": "branch_id", "type": "str", "description": "ID de sucursal", "required": False}]),
    "ia_chat_secure": _t("ia_chat_secure",
        "Endpoint seguro de chat con IA",
        "settings", "/api/ia/chat/secure", "GET",
        [{"name": "mensaje", "type": "str", "description": "Mensaje del usuario", "required": True}]),
    "supabase_estado": _t("supabase_estado",
        "Estado de la conexion con Supabase",
        "settings", "/api/supabase/estado", "GET", []),
    "supabase_config": _t("supabase_config",
        "Obtiene la configuracion de Supabase",
        "settings", "/api/supabase/config", "GET", [],
        role="administrador"),
    "save_supabase_config": _t("save_supabase_config",
        "Guarda la configuracion de Supabase",
        "settings", "/api/supabase/config", "POST",
        [{"name": "url", "type": "str", "description": "URL de Supabase", "required": True},
         {"name": "anon_key", "type": "str", "description": "Anon key", "required": True}],
        role="administrador"),
    "supabase_setup": _t("supabase_setup",
        "Configura la conexion con Supabase",
        "settings", "/api/supabase/setup", "POST",
        [{"name": "url", "type": "str", "description": "URL de Supabase", "required": True},
         {"name": "anon_key", "type": "str", "description": "Anon key", "required": True}],
        role="administrador"),
    "test_supabase": _t("test_supabase",
        "Prueba la conexion con Supabase",
        "settings", "/api/supabase/test", "POST", [],
        role="administrador"),
    "pull_supabase": _t("pull_supabase",
        "Descarga datos desde Supabase",
        "settings", "/api/supabase/pull", "POST",
        [{"name": "tabla", "type": "str", "description": "Tabla a descargar", "required": False}],
        role="administrador"),
    "push_supabase": _t("push_supabase",
        "Sube datos a Supabase",
        "settings", "/api/supabase/push", "POST",
        [{"name": "tabla", "type": "str", "description": "Tabla a subir", "required": False}],
        role="administrador"),
    "sync_all": _t("sync_all",
        "Sincroniza todas las tablas con Supabase",
        "settings", "/api/supabase/sync-all", "POST", [],
        role="administrador"),
    "supabase_sql": _t("supabase_sql",
        "Ejecuta una consulta SQL en Supabase",
        "settings", "/api/supabase/sql", "GET",
        [{"name": "query", "type": "str", "description": "Consulta SQL", "required": True}],
        role="desarrollador"),
    "sync_full": _t("sync_full",
        "Sincronizacion completa bidireccional con Supabase",
        "settings", "/api/supabase/sync-full", "POST", [],
        role="administrador"),

    # ══════════════════════════════════════════
    #  VALIDACION (val_bp) — 9 herramientas
    # ══════════════════════════════════════════
    "calcular_venta": _t("calcular_venta",
        "Calcula los totales de una venta: subtotal, impuesto, descuento, total",
        "validacion", "/api/ventas/calcular", "GET",
        [{"name": "productos", "type": "list", "description": "Lista de items", "required": True},
         {"name": "descuento", "type": "float", "description": "Descuento global", "required": False}]),
    "validar_stock": _t("validar_stock",
        "Valida que haya stock suficiente para una venta",
        "validacion", "/api/ventas/validar-stock", "GET",
        [{"name": "productos", "type": "list", "description": "Lista de {producto_id, cantidad}", "required": True}]),
    "validar_totales": _t("validar_totales",
        "Valida los totales de una venta",
        "validacion", "/api/ventas/validar-totales", "GET",
        [{"name": "subtotal", "type": "float", "description": "Subtotal", "required": True},
         {"name": "descuento", "type": "float", "description": "Descuento", "required": True},
         {"name": "total", "type": "float", "description": "Total", "required": True}]),
    "cierre_calcular": _t("cierre_calcular",
        "Calcula los datos del cierre de caja",
        "validacion", "/api/ventas/cierre-calcular", "GET", []),
    "generar_id": _t("generar_id",
        "Genera un ID unico para venta u otro registro",
        "validacion", "/api/ventas/generar-id", "GET", []),
    "cifrar": _t("cifrar",
        "Cifra un texto con AES",
        "validacion", "/api/util/cifrar", "GET",
        [{"name": "texto", "type": "str", "description": "Texto a cifrar", "required": True}]),
    "descifrar": _t("descifrar",
        "Descifra un texto cifrado con AES",
        "validacion", "/api/util/descifrar", "GET",
        [{"name": "texto_cifrado", "type": "str", "description": "Texto cifrado", "required": True}]),
    "sanitize": _t("sanitize",
        "Sanitiza un texto eliminando caracteres peligrosos",
        "validacion", "/api/util/sanitize", "GET",
        [{"name": "texto", "type": "str", "description": "Texto a sanitizar", "required": True}]),
    "sqli_check": _t("sqli_check",
        "Verifica si un texto contiene patrones de inyeccion SQL",
        "validacion", "/api/util/sqli-check", "GET",
        [{"name": "texto", "type": "str", "description": "Texto a verificar", "required": True}]),

    # ══════════════════════════════════════════
    #  IA ASISTANT (assistant_bp) — 9 herramientas
    # ══════════════════════════════════════════
    "ia_chat": _t("ia_chat",
        "Chat con el asistente de IA",
        "ia_assistant", "/chat", "GET",
        [{"name": "mensaje", "type": "str", "description": "Mensaje del usuario", "required": True}]),
    "ia_ping": _t("ia_ping",
        "Ping al servicio de IA",
        "ia_assistant", "/ping", "GET", [], auth=False),
    "ia_status": _t("ia_status",
        "Estado del servicio de IA",
        "ia_assistant", "/status", "GET", [], auth=False),
    "ia_set_role": _t("ia_set_role",
        "Establece el rol del asistente de IA",
        "ia_assistant", "/role", "GET",
        [{"name": "role", "type": "str", "description": "Rol a establecer", "required": True}]),
    "ia_alerts": _t("ia_alerts",
        "Alertas generadas por la IA",
        "ia_assistant", "/alerts", "GET", []),
    "memory_save": _t("memory_save",
        "Guarda informacion en la memoria de la IA",
        "ia_assistant", "/memory/save", "GET",
        [{"name": "key", "type": "str", "description": "Clave", "required": True},
         {"name": "value", "type": "str", "description": "Valor", "required": True}]),
    "memory_recall": _t("memory_recall",
        "Recupera informacion de la memoria de la IA",
        "ia_assistant", "/memory/recall", "GET",
        [{"name": "key", "type": "str", "description": "Clave a buscar", "required": True}]),
    "memory_search": _t("memory_search",
        "Busca en la memoria de la IA por texto",
        "ia_assistant", "/memory/search", "GET",
        [{"name": "query", "type": "str", "description": "Texto de busqueda", "required": True}]),
    "memory_forget": _t("memory_forget",
        "Elimina informacion de la memoria de la IA",
        "ia_assistant", "/memory/forget", "GET",
        [{"name": "key", "type": "str", "description": "Clave a eliminar", "required": True}]),
    "memory_summary": _t("memory_summary",
        "Resumen de toda la memoria de la IA",
        "ia_assistant", "/memory/summary", "GET", []),

    # ══════════════════════════════════════════
    #  GENERAL (app) — 3 herramientas
    # ══════════════════════════════════════════
    "health_check": _t("health_check",
        "Verifica el estado del servidor API",
        "general", "/api/health", "GET", [], auth=False),
    "config_publica": _t("config_publica",
        "Obtiene la configuracion publica del sistema (nombre, moneda, impuesto)",
        "general", "/api/config/publica", "GET", [], auth=False),
    "biometric_check": _t("biometric_check",
        "Verifica disponibilidad de biometria en el dispositivo",
        "general", "/api/biometric/check", "GET", [], auth=False),
    # ══════════════════════════════════════════════════════════
    #  IMPORTACION INTELIGENTE (app.py) — 3 herramientas
    # ══════════════════════════════════════════════════════════
    "reconstruir_productos": _t("reconstruir_productos",
        "Sincroniza una lista de productos con la base de datos SQLite. Reemplaza el catalogo completo y actualiza inventario_general.",
        "importacion", "/api/reconstruir-desde-productos", "POST",
        [{"name": "productos", "type": "list", "description": "Lista de productos con id, nombre, precio, costoUnitario, categoria, um", "required": True},
         {"name": "admin_id", "type": "str", "description": "ID del administrador (default: system)", "required": False}],
        role="administrador"),

    "importar_catalogo_inventario": _t("importar_catalogo_inventario",
        "Importa todos los productos del catalogo al inventario general. Nuevos: stock 0. Existentes: conserva stock actual.",
        "importacion", "/api/inventario/importar-catalogo", "POST",
        [],
        role="administrador"),

    "obtener_productos_catalogo": _t("obtener_productos_catalogo",
        "Retorna todos los productos del catalogo desde la base de datos SQLite.",
        "importacion", "/api/productos", "GET",
        [],
        role="administrador"),
    # ══════════════════════════════════════════════
    #  DEV METRICS (dev_metrics_bp) — 4 herramientas
    # ══════════════════════════════════════════════
    "dev_metricas_completas": _t("dev_metricas_completas",
        "Obtiene todas las metricas del sistema: RAM, almacenamiento y formulas de inventario en tiempo real",
        "dev", "/api/dev/metrics", "GET",
        [],
        role="desarrollador"),

    "dev_metricas_ram": _t("dev_metricas_ram",
        "Obtiene metricas de memoria RAM del proceso Flask y del sistema",
        "dev", "/api/dev/metrics/ram", "GET",
        [],
        role="desarrollador"),

    "dev_metricas_almacenamiento": _t("dev_metricas_almacenamiento",
        "Obtiene metricas de almacenamiento: tamano de BD SQLite y uso de disco",
        "dev", "/api/dev/metrics/storage", "GET",
        [],
        role="desarrollador"),

    # ══════════════════════════════════════════════
    #  DICCIONARIO (diccionario_bp) — 3 herramientas
    # ══════════════════════════════════════════════
    "diccionario_sinonimos": _t("diccionario_sinonimos",
        "Busca sinonimos de una palabra o producto. Parametro q= palabra a buscar",
        "diccionario", "/api/diccionario/sinonimos", "GET",
        [{"name": "q", "type": "str", "description": "Palabra a buscar sinonimos", "required": True}]),

    "diccionario_definicion": _t("diccionario_definicion",
        "Define terminos comerciales: margen, ganancia, inventario, KPI, cross-selling, ABC, etc",
        "diccionario", "/api/diccionario/definicion", "GET",
        [{"name": "q", "type": "str", "description": "Termino comercial a definir", "required": True}]),

    "diccionario_corregir": _t("diccionario_corregir",
        "Corrige ortografia de palabras en consultas del usuario",
        "diccionario", "/api/diccionario/corregir", "GET",
        [{"name": "q", "type": "str", "description": "Palabra a corregir", "required": True}]),

    "dev_metricas_inventario": _t("dev_metricas_inventario",
        "Calcula formulas de inventario: margen bruto, cobertura de stock, ganancia potencial, top 5 por valor",
        "dev", "/api/dev/metrics/inventario", "GET",
        [],
        role="desarrollador"),

}


# ══════════════════════════════════════════════
#  FUNCIONES DE CONSULTA
# ══════════════════════════════════════════════

def get_tool(name: str) -> Optional[ToolDefinition]:
    return TOOL_CATALOG.get(name)

def get_tools_by_category(category: str) -> List[ToolDefinition]:
    return [t for t in TOOL_CATALOG.values() if t.category == category]

def get_all_tools() -> Dict[str, ToolDefinition]:
    return dict(TOOL_CATALOG)

def search_tools(query: str) -> List[ToolDefinition]:
    q = query.lower()
    return [t for t in TOOL_CATALOG.values()
            if q in t.name.lower() or q in t.description.lower() or q in t.category.lower()]

def get_tool_summary(tool: ToolDefinition) -> str:
    params_str = ", ".join(
        f"{p['name']}" + ("*" if p.get("required") else "")
        for p in tool.params
    )
    role = f" [{tool.requires_role}]" if tool.requires_role else ""
    return f"- {tool.name}({params_str}): {tool.description}{role}"

def get_catalog_stats() -> Dict[str, int]:
    """Retorna estadisticas del catalogo."""
    cats = {}
    for t in TOOL_CATALOG.values():
        cats[t.category] = cats.get(t.category, 0) + 1
    return {"total": len(TOOL_CATALOG), "categories": cats}
