from tools.base import _t

ADMIN_TOOLS = {
    "listar_usuarios": _t("listar_usuarios",
        "Lista todos los usuarios del sistema con sus roles y estado",
        "admin", "/api/usuarios", "GET",
        [{"name": "rol", "type": "str", "description": "Filtrar por rol", "required": False}],
        role="administrador"),
    "crear_usuario": _t("crear_usuario",
        "Crea un nuevo usuario con nombre, username, password y rol",
        "admin", "/api/usuarios/crear", "POST",
        [{"name": "username", "type": "str", "description": "Nombre de usuario", "required": True},
         {"name": "nombre", "type": "str", "description": "Nombre completo", "required": True},
         {"name": "password", "type": "str", "description": "Contrasena", "required": True},
         {"name": "rol", "type": "str", "description": "administrador, vendedor, desarrollador", "required": True}],
        role="administrador"),
    "desactivar_usuario": _t("desactivar_usuario",
        "Desactiva un usuario del sistema",
        "admin", "/api/usuarios/<usuario_id>", "DELETE",
        [{"name": "usuario_id", "type": "str", "description": "ID del usuario", "required": True}],
        role="administrador"),
    "reset_password": _t("reset_password",
        "Resetea la contrasena de un usuario",
        "admin", "/api/usuarios/<usuario_id>/reset-password", "POST",
        [{"name": "usuario_id", "type": "str", "description": "ID del usuario", "required": True},
         {"name": "nueva_password", "type": "str", "description": "Nueva contrasena", "required": True}],
        role="administrador"),
    "listar_licencias": _t("listar_licencias",
        "Lista todas las licencias del sistema",
        "admin", "/api/licencias", "GET", [],
        role="administrador"),
    "crear_licencia": _t("crear_licencia",
        "Crea una nueva licencia para un dispositivo",
        "admin", "/api/licencias/crear", "POST",
        [{"name": "device_id", "type": "str", "description": "ID del dispositivo", "required": True},
         {"name": "tipo", "type": "str", "description": "Tipo de licencia", "required": True}],
        role="desarrollador"),
    "verificar_licencia": _t("verificar_licencia",
        "Verifica el estado de una licencia de un administrador",
        "admin", "/api/licencias/verificar/<admin_id>", "GET",
        [{"name": "admin_id", "type": "str", "description": "ID del admin", "required": True}],
        role="administrador"),
    "desactivar_licencia": _t("desactivar_licencia",
        "Desactiva una licencia",
        "admin", "/api/licencias/<licencia_id>", "DELETE",
        [{"name": "licencia_id", "type": "str", "description": "ID de licencia", "required": True}],
        role="desarrollador"),
    "get_privilegios": _t("get_privilegios",
        "Obtiene los privilegios de un rol especifico",
        "admin", "/api/privilegios/<rol>", "GET",
        [{"name": "rol", "type": "str", "description": "Nombre del rol", "required": True}],
        role="administrador"),
    "set_privilegios": _t("set_privilegios",
        "Establece los privilegios de un rol",
        "admin", "/api/privilegios/<rol>", "PUT",
        [{"name": "rol", "type": "str", "description": "Nombre del rol", "required": True},
         {"name": "privilegios", "type": "list", "description": "Lista de privilegios", "required": True}],
        role="desarrollador"),
    "reset_privilegios": _t("reset_privilegios",
        "Restablece los privilegios de un rol a los valores por defecto",
        "admin", "/api/privilegios/<rol>/restablecer", "POST",
        [{"name": "rol", "type": "str", "description": "Nombre del rol", "required": True}],
        role="desarrollador"),
}
