from tools.base import _t

ANALYTIC_TOOLS = {
    "dashboard_general": _t("dashboard_general",
        "Dashboard general con KPIs y resumen del negocio",
        "analytics", "/dashboard", "GET",
        [{"name": "dias", "type": "int", "description": "Periodo en dias", "required": False}]),
    "analytics_abc": _t("analytics_abc",
        "Analisis ABC de productos: clasifica por contribucion a ingresos",
        "analytics", "/analytics/abc", "GET", []),
    "analytics_cross_selling": _t("analytics_cross_selling",
        "Analisis de cross-selling: productos que se venden juntos",
        "analytics", "/analytics/cross-selling", "GET", []),
    "analytics_prices": _t("analytics_prices",
        "Analisis de precios: comparativa y optimizacion de precios",
        "analytics", "/analytics/prices", "GET", []),
    "analytics_kpis": _t("analytics_kpis",
        "KPIs del negocio: ventas, clientes, ticket promedio, etc",
        "analytics", "/kpis", "GET",
        [{"name": "dias", "type": "int", "description": "Periodo en dias", "required": False}]),
    "predict_dashboard": _t("predict_dashboard",
        "Dashboard predictivo: tendencias y pronosticos",
        "analytics", "/predict/dashboard", "GET", []),
    "predictor": _t("predictor",
        "Motor predictivo: pronostico de ventas y demanda",
        "analytics", "/predictor", "GET",
        [{"name": "dias", "type": "int", "description": "Dias a pronosticar", "required": False}]),
    "fraud_dashboard": _t("fraud_dashboard",
        "Dashboard de deteccion de fraude y anomalias",
        "analytics", "/fraud/dashboard", "GET", []),
    "fraud": _t("fraud",
        "Analisis de fraude y transacciones sospechosas",
        "analytics", "/fraud", "GET", []),
    "prices": _t("prices",
        "Gestion y analisis de precios de productos",
        "analytics", "/prices", "GET", []),
    "analytics_combined": _t("analytics_combined",
        "Endpoint combinado de analytics para compatibilidad",
        "analytics", "/analytics", "GET", []),
    "alertas_analytics": _t("alertas_analytics",
        "Sistema de alertas basado en analytics",
        "analytics", "/alerts", "GET", []),
}
