from tools.base import _t

GENERAL_TOOLS = {
    "health_check": _t("health_check",
        "Verifica el estado del servidor API",
        "general", "/api/health", "GET", [], auth=False),
    "config_publica": _t("config_publica",
        "Obtiene la configuracion publica del sistema (nombre, moneda, impuesto)",
        "general", "/api/config/publica", "GET", [], auth=False),
    "biometric_check": _t("biometric_check",
        "Verifica disponibilidad de biometria en el dispositivo",
        "general", "/api/biometric/check", "GET", [], auth=False),
    "dev_metricas_completas": _t("dev_metricas_completas",
        "Obtiene todas las metricas del sistema: RAM, almacenamiento y formulas de inventario en tiempo real",
        "dev", "/api/dev/metrics", "GET",
        [],
        role="desarrollador"),
    "dev_metricas_ram": _t("dev_metricas_ram",
        "Obtiene metricas de memoria RAM del proceso Flask y del sistema",
        "dev", "/api/dev/metrics/ram", "GET",
        [],
        role="desarrollador"),
    "dev_metricas_almacenamiento": _t("dev_metricas_almacenamiento",
        "Obtiene metricas de almacenamiento: tamano de BD SQLite y uso de disco",
        "dev", "/api/dev/metrics/storage", "GET",
        [],
        role="desarrollador"),
    "diccionario_sinonimos": _t("diccionario_sinonimos",
        "Busca sinonimos de una palabra o producto. Parametro q= palabra a buscar",
        "diccionario", "/api/diccionario/sinonimos", "GET",
        [{"name": "q", "type": "str", "description": "Palabra a buscar sinonimos", "required": True}]),
    "diccionario_definicion": _t("diccionario_definicion",
        "Define terminos comerciales: margen, ganancia, inventario, KPI, cross-selling, ABC, etc",
        "diccionario", "/api/diccionario/definicion", "GET",
        [{"name": "q", "type": "str", "description": "Termino comercial a definir", "required": True}]),
    "diccionario_corregir": _t("diccionario_corregir",
        "Corrige ortografia de palabras en consultas del usuario",
        "diccionario", "/api/diccionario/corregir", "GET",
        [{"name": "q", "type": "str", "description": "Palabra a corregir", "required": True}]),
    "dev_metricas_inventario": _t("dev_metricas_inventario",
        "Calcula formulas de inventario: margen bruto, cobertura de stock, ganancia potencial, top 5 por valor",
        "dev", "/api/dev/metrics/inventario", "GET",
        [],
        role="desarrollador"),
}
