from tools.base import _t

IA_TOOLS = {
    "ia_chat": _t("ia_chat",
        "Chat con el asistente de IA",
        "ia_assistant", "/chat", "GET",
        [{"name": "mensaje", "type": "str", "description": "Mensaje del usuario", "required": True}]),
    "ia_ping": _t("ia_ping",
        "Ping al servicio de IA",
        "ia_assistant", "/ping", "GET", [], auth=False),
    "ia_status": _t("ia_status",
        "Estado del servicio de IA",
        "ia_assistant", "/status", "GET", [], auth=False),
    "ia_set_role": _t("ia_set_role",
        "Establece el rol del asistente de IA",
        "ia_assistant", "/role", "GET",
        [{"name": "role", "type": "str", "description": "Rol a establecer", "required": True}]),
    "ia_alerts": _t("ia_alerts",
        "Alertas generadas por la IA",
        "ia_assistant", "/alerts", "GET", []),
    "memory_save": _t("memory_save",
        "Guarda informacion en la memoria de la IA",
        "ia_assistant", "/memory/save", "GET",
        [{"name": "key", "type": "str", "description": "Clave", "required": True},
         {"name": "value", "type": "str", "description": "Valor", "required": True}]),
    "memory_recall": _t("memory_recall",
        "Recupera informacion de la memoria de la IA",
        "ia_assistant", "/memory/recall", "GET",
        [{"name": "key", "type": "str", "description": "Clave a buscar", "required": True}]),
    "memory_search": _t("memory_search",
        "Busca en la memoria de la IA por texto",
        "ia_assistant", "/memory/search", "GET",
        [{"name": "query", "type": "str", "description": "Texto de busqueda", "required": True}]),
    "memory_forget": _t("memory_forget",
        "Elimina informacion de la memoria de la IA",
        "ia_assistant", "/memory/forget", "GET",
        [{"name": "key", "type": "str", "description": "Clave a eliminar", "required": True}]),
    "memory_summary": _t("memory_summary",
        "Resumen de toda la memoria de la IA",
        "ia_assistant", "/memory/summary", "GET", []),
}
