from tools.base import _t

INVENTARIO_TOOLS = {
    "get_catalogo": _t("get_catalogo",
        "Obtiene el catalogo completo de productos con precios y categorias",
        "inventario", "/api/catalogo", "GET",
        [{"name": "categoria", "type": "str", "description": "Filtrar por categoria", "required": False}]),
    "inventario_general": _t("inventario_general",
        "Obtiene el inventario general consolidado con stock actual",
        "inventario", "/api/inventario/general", "GET",
        [{"name": "categoria", "type": "str", "description": "Filtrar por categoria", "required": False}]),
    "entrada_producto": _t("entrada_producto",
        "Registra una entrada de mercancia a un producto",
        "inventario", "/api/inventario/entrada", "POST",
        [{"name": "producto_id", "type": "str", "description": "ID del producto", "required": True},
         {"name": "cantidad", "type": "float", "description": "Cantidad entrante", "required": True},
         {"name": "costo", "type": "float", "description": "Costo unitario", "required": False},
         {"name": "motivo", "type": "str", "description": "Motivo de la entrada", "required": False}],
        role="vendedor"),
    "stock_masivo": _t("stock_masivo",
        "Actualiza stock de multiples productos en una sola operacion",
        "inventario", "/api/stock/masivo", "POST",
        [{"name": "productos", "type": "list", "description": "Lista de {producto_id, cantidad}", "required": True}],
        role="vendedor"),
    "importar_validado": _t("importar_validado",
        "Importacion profesional con validacion dry-run + transaccion atomica",
        "inventario", "/api/importar-validado", "POST",
        [{"name": "productos", "type": "list", "description": "Lista de productos a importar", "required": True},
         {"name": "ejecutar", "type": "bool", "description": "True para ejecutar, False solo valida", "required": False}],
        role="vendedor"),
    "importar_catalogo": _t("importar_catalogo",
        "Importa catalogo de productos desde datos externos",
        "inventario", "/api/inventario/importar-catalogo", "POST",
        [{"name": "productos", "type": "list", "description": "Lista de productos", "required": True}],
        role="vendedor"),
    "sync_catalogo": _t("sync_catalogo",
        "Sincroniza el catalogo desde el frontend al backend",
        "inventario", "/api/catalogo/sync", "POST",
        [{"name": "productos", "type": "list", "description": "Lista de productos", "required": True}],
        role="vendedor"),
    "sync_desde_inventario": _t("sync_desde_inventario",
        "Sincroniza productos desde inventario general al catalogo",
        "inventario", "/api/catalogo/sync-desde-inventario", "POST", [],
        role="administrador"),
    "sincronizar_completo": _t("sincronizar_completo",
        "Sincronizacion completa de todas las tablas",
        "inventario", "/api/sincronizar-completo", "POST", [],
        role="administrador"),
    "eliminar_inventario_general": _t("eliminar_inventario_general",
        "Elimina un producto del inventario general",
        "inventario", "/api/inventario/general/eliminar", "POST",
        [{"name": "producto_id", "type": "str", "description": "ID del producto", "required": True}],
        role="administrador"),
    "limpiar_tablas": _t("limpiar_tablas",
        "Limpia todas las tablas del sistema (operacion destructiva)",
        "inventario", "/api/limpiar-tablas", "POST", [],
        role="desarrollador"),
    "inventario_diario": _t("inventario_diario",
        "Obtiene el inventario diario asignado a un vendedor",
        "inventario", "/api/inventario/diario/<vendedor_id>", "GET",
        [{"name": "vendedor_id", "type": "str", "description": "ID del vendedor", "required": True}]),
    "asignar_inventario": _t("asignar_inventario",
        "Asigna inventario diario a un vendedor",
        "inventario", "/api/inventario/asignar-diario", "POST",
        [{"name": "vendedor_id", "type": "str", "description": "ID del vendedor", "required": True},
         {"name": "productos", "type": "list", "description": "Lista de productos con cantidades", "required": True}],
        role="administrador"),
    "conteo_vendedor": _t("conteo_vendedor",
        "Registra conteo de inventario realizado por el vendedor",
        "inventario", "/api/inventario/diario/conteo", "POST",
        [{"name": "vendedor_id", "type": "str", "description": "ID del vendedor", "required": True},
         {"name": "conteo", "type": "list", "description": "Lista de {producto_id, cantidad}", "required": True}],
        role="vendedor"),
    "cierre_vendedor": _t("cierre_vendedor",
        "Cierra el inventario diario de un vendedor",
        "inventario", "/api/inventario/diario/cierre", "POST",
        [{"name": "vendedor_id", "type": "str", "description": "ID del vendedor", "required": True}],
        role="vendedor"),
    "historial_entradas": _t("historial_entradas",
        "Historial de entradas de mercancia",
        "inventario", "/api/inventario/entradas", "GET",
        [{"name": "dias", "type": "int", "description": "Dias a consultar", "required": False}]),
    "historial_cierres": _t("historial_cierres",
        "Historial de cierres de inventario de un vendedor",
        "inventario", "/api/inventario/diario/historial/<vendedor_id>", "GET",
        [{"name": "vendedor_id", "type": "str", "description": "ID del vendedor", "required": True}]),
    "cierre_admin": _t("cierre_admin",
        "Cierre administrativo de inventario",
        "inventario", "/api/inventario/cierre-admin", "POST", [],
        role="administrador"),
}
