from tools.base import _t

LEALTAD_TOOLS = {
    "loyalty_enroll": _t("loyalty_enroll",
        "Inscribe un cliente en el programa de lealtad",
        "lealtad", "/enroll", "POST",
        [{"name": "cliente_id", "type": "str", "description": "ID del cliente", "required": True}]),
    "loyalty_points": _t("loyalty_points",
        "Consulta los puntos de un cliente",
        "lealtad", "/points", "GET",
        [{"name": "cliente_id", "type": "str", "description": "ID del cliente", "required": True}]),
    "loyalty_add_points": _t("loyalty_add_points",
        "Agrega puntos a un cliente",
        "lealtad", "/points/add", "POST",
        [{"name": "cliente_id", "type": "str", "description": "ID del cliente", "required": True},
         {"name": "puntos", "type": "int", "description": "Puntos a agregar", "required": True}],
        role="vendedor"),
    "loyalty_redeem": _t("loyalty_redeem",
        "Canjea puntos de un cliente por una recompensa",
        "lealtad", "/points/redeem", "POST",
        [{"name": "cliente_id", "type": "str", "description": "ID del cliente", "required": True},
         {"name": "puntos", "type": "int", "description": "Puntos a canjear", "required": True}]),
    "loyalty_history": _t("loyalty_history",
        "Historial de movimientos de puntos de un cliente",
        "lealtad", "/history", "GET",
        [{"name": "cliente_id", "type": "str", "description": "ID del cliente", "required": True}]),
    "loyalty_leaderboard": _t("loyalty_leaderboard",
        "Ranking de clientes con mas puntos",
        "lealtad", "/leaderboard", "GET", []),
    "loyalty_headless_order": _t("loyalty_headless_order",
        "Crea un pedido sin interfaz (headless) con puntos",
        "lealtad", "/headless/order", "POST",
        [{"name": "cliente_id", "type": "str", "description": "ID del cliente", "required": True},
         {"name": "productos", "type": "list", "description": "Lista de productos", "required": True}]),
}
