from tools.base import _t

SEGURIDAD_TOOLS = {
    "pci_tokenize": _t("pci_tokenize",
        "Tokeniza datos de pago (cumplimiento PCI-DSS)",
        "seguridad", "/pci/tokenize", "POST",
        [{"name": "card_data", "type": "str", "description": "Datos de tarjeta", "required": True}]),
    "pci_mask": _t("pci_mask",
        "Enmascara datos sensibles de tarjeta",
        "seguridad", "/pci/mask", "POST",
        [{"name": "card_number", "type": "str", "description": "Numero de tarjeta", "required": True}]),
    "pci_audit": _t("pci_audit",
        "Auditoria de cumplimiento PCI-DSS",
        "seguridad", "/pci/audit", "GET", [],
        role="administrador"),
    "het_status": _t("het_status",
        "Estado del sistema de deteccion de amenazas (HET)",
        "seguridad", "/het/status", "GET", []),
    "het_alerts": _t("het_alerts",
        "Alertas de seguridad del sistema HET",
        "seguridad", "/het/alerts", "GET", []),
    "ws_status": _t("ws_status",
        "Estado del sistema WebSocket",
        "seguridad", "/ws/status", "GET", []),
    "omnichannel_status": _t("omnichannel_status",
        "Estado del sistema omnicanal",
        "seguridad", "/omnichannel/status", "GET", []),
}
