from tools.base import _t

SETTING_TOOLS = {
    "export_backup": _t("export_backup",
        "Exporta backup completo de la base de datos",
        "settings", "/api/backup", "GET", [],
        role="administrador"),
    "biometric_setup": _t("biometric_setup",
        "Configura la autenticacion biometrica",
        "settings", "/api/biometric/setup", "GET", []),
    "get_state": _t("get_state",
        "Obtiene el estado guardado de la aplicacion",
        "settings", "/api/state", "GET", []),
    "save_state": _t("save_state",
        "Guarda el estado de la aplicacion",
        "settings", "/api/state", "POST",
        [{"name": "state", "type": "dict", "description": "Estado a guardar", "required": True}]),
    "get_status": _t("get_status",
        "Estado general del sistema",
        "settings", "/api/status", "GET", [], auth=False),
    "api_ping": _t("api_ping",
        "Ping al servidor para verificar conectividad",
        "settings", "/api/ping", "GET", [], auth=False),
    "health_full": _t("health_full",
        "Health check completo del sistema",
        "settings", "/api/health/full", "GET", []),
    "debug_health": _t("debug_health",
        "Health check con informacion de debug",
        "settings", "/api/debug/health", "GET", [],
        role="desarrollador"),
    "payment_tokenize": _t("payment_tokenize",
        "Tokeniza datos de pago para transaccion segura",
        "settings", "/api/payment/tokenize", "GET",
        [{"name": "card_data", "type": "str", "description": "Datos de tarjeta", "required": True}]),
    "api_sse": _t("api_sse",
        "Server-Sent Events endpoint",
        "settings", "/api/sse", "GET", []),
    "branch_info": _t("branch_info",
        "Informacion de la sucursal actual",
        "settings", "/api/branch/info", "GET", []),
    "branch_filter": _t("branch_filter",
        "Filtro por sucursal",
        "settings", "/api/branch/filter", "GET",
        [{"name": "branch_id", "type": "str", "description": "ID de sucursal", "required": False}]),
    "ia_chat_secure": _t("ia_chat_secure",
        "Endpoint seguro de chat con IA",
        "settings", "/api/ia/chat/secure", "GET",
        [{"name": "mensaje", "type": "str", "description": "Mensaje del usuario", "required": True}]),
    "supabase_estado": _t("supabase_estado",
        "Estado de la conexion con Supabase",
        "settings", "/api/supabase/estado", "GET", []),
    "supabase_config": _t("supabase_config",
        "Obtiene la configuracion de Supabase",
        "settings", "/api/supabase/config", "GET", [],
        role="administrador"),
    "save_supabase_config": _t("save_supabase_config",
        "Guarda la configuracion de Supabase",
        "settings", "/api/supabase/config", "POST",
        [{"name": "url", "type": "str", "description": "URL de Supabase", "required": True},
         {"name": "anon_key", "type": "str", "description": "Anon key", "required": True}],
        role="administrador"),
    "supabase_setup": _t("supabase_setup",
        "Configura la conexion con Supabase",
        "settings", "/api/supabase/setup", "POST",
        [{"name": "url", "type": "str", "description": "URL de Supabase", "required": True},
         {"name": "anon_key", "type": "str", "description": "Anon key", "required": True}],
        role="administrador"),
    "test_supabase": _t("test_supabase",
        "Prueba la conexion con Supabase",
        "settings", "/api/supabase/test", "POST", [],
        role="administrador"),
    "pull_supabase": _t("pull_supabase",
        "Descarga datos desde Supabase",
        "settings", "/api/supabase/pull", "POST",
        [{"name": "tabla", "type": "str", "description": "Tabla a descargar", "required": False}],
        role="administrador"),
    "push_supabase": _t("push_supabase",
        "Sube datos a Supabase",
        "settings", "/api/supabase/push", "POST",
        [{"name": "tabla", "type": "str", "description": "Tabla a subir", "required": False}],
        role="administrador"),
    "sync_all": _t("sync_all",
        "Sincroniza todas las tablas con Supabase",
        "settings", "/api/supabase/sync-all", "POST", [],
        role="administrador"),
    "supabase_sql": _t("supabase_sql",
        "Ejecuta una consulta SQL en Supabase",
        "settings", "/api/supabase/sql", "GET",
        [{"name": "query", "type": "str", "description": "Consulta SQL", "required": True}],
        role="desarrollador"),
    "sync_full": _t("sync_full",
        "Sincronizacion completa bidireccional con Supabase",
        "settings", "/api/supabase/sync-full", "POST", [],
        role="administrador"),
}
