from tools.base import _t

TIENDA_TOOLS = {
    "listar_productos_tienda": _t("listar_productos_tienda",
        "Lista productos disponibles en la tienda online",
        "tienda", "/api/productos", "GET",
        [{"name": "categoria", "type": "str", "description": "Filtrar por categoria", "required": False}]),
    "producto_detalle": _t("producto_detalle",
        "Obtiene detalle completo de un producto",
        "tienda", "/api/productos/<producto_id>", "GET",
        [{"name": "producto_id", "type": "str", "description": "ID del producto", "required": True}]),
    "subir_imagen_producto": _t("subir_imagen_producto",
        "Sube o actualiza la imagen de un producto (base64)",
        "tienda", "/api/productos/<producto_id>/imagen", "POST",
        [{"name": "producto_id", "type": "str", "description": "ID del producto", "required": True}],
        role="vendedor"),
    "generar_qr_productos": _t("generar_qr_productos",
        "Genera codigos QR para hasta 40 productos",
        "tienda", "/api/productos/qr", "GET", [],
        role="vendedor"),
    "listar_clientes": _t("listar_clientes",
        "Lista todos los clientes registrados",
        "tienda", "/api/clientes", "GET",
        [{"name": "buscar", "type": "str", "description": "Termino de busqueda", "required": False}]),
    "perfil_cliente": _t("perfil_cliente",
        "Perfil publico de un cliente",
        "tienda", "/api/clientes/<cliente_id>", "GET",
        [{"name": "cliente_id", "type": "str", "description": "ID del cliente", "required": True}]),
    "login_cliente": _t("login_cliente",
        "Inicio de sesion para clientes de la tienda",
        "tienda", "/api/clientes/login", "POST",
        [{"name": "email", "type": "str", "description": "Email del cliente", "required": True},
         {"name": "password", "type": "str", "description": "Contrasena", "required": True}],
        auth=False),
    "registrar_cliente": _t("registrar_cliente",
        "Registra un nuevo cliente en la tienda",
        "tienda", "/api/clientes/registrar", "POST",
        [{"name": "nombre", "type": "str", "description": "Nombre", "required": True},
         {"name": "email", "type": "str", "description": "Email", "required": True},
         {"name": "password", "type": "str", "description": "Contrasena", "required": True}],
        auth=False),
    "crear_pedido": _t("crear_pedido",
        "Crea un nuevo pedido en la tienda online",
        "tienda", "/api/pedidos", "POST",
        [{"name": "cliente_id", "type": "str", "description": "ID del cliente", "required": True},
         {"name": "productos", "type": "list", "description": "Lista de items del pedido", "required": True}],
        auth=False),
    "obtener_pedido": _t("obtener_pedido",
        "Obtiene detalle de un pedido especifico",
        "tienda", "/api/pedidos/<pedido_id>", "GET",
        [{"name": "pedido_id", "type": "str", "description": "ID del pedido", "required": True}]),
    "actualizar_estado_pedido": _t("actualizar_estado_pedido",
        "Actualiza el estado de un pedido",
        "tienda", "/api/pedidos/<pedido_id>/estado", "POST",
        [{"name": "pedido_id", "type": "str", "description": "ID del pedido", "required": True},
         {"name": "estado", "type": "str", "description": "Nuevo estado", "required": True}],
        role="vendedor"),
    "resumen_pedidos": _t("resumen_pedidos",
        "Resumen de todos los pedidos de la tienda",
        "tienda", "/api/pedidos/resumen", "GET", []),
    "listar_tiendas": _t("listar_tiendas",
        "Lista todas las tiendas registradas",
        "tienda", "/api/tiendas", "GET", []),
    "eliminar_tienda": _t("eliminar_tienda",
        "Elimina o actualiza una tienda",
        "tienda", "/api/tiendas/<tienda_id>", "DELETE",
        [{"name": "tienda_id", "type": "str", "description": "ID de la tienda", "required": True}],
        role="administrador"),
}
