from tools.base import _t

VALIDACION_TOOLS = {
    "calcular_venta": _t("calcular_venta",
        "Calcula los totales de una venta: subtotal, impuesto, descuento, total",
        "validacion", "/api/ventas/calcular", "GET",
        [{"name": "productos", "type": "list", "description": "Lista de items", "required": True},
         {"name": "descuento", "type": "float", "description": "Descuento global", "required": False}]),
    "validar_stock": _t("validar_stock",
        "Valida que haya stock suficiente para una venta",
        "validacion", "/api/ventas/validar-stock", "GET",
        [{"name": "productos", "type": "list", "description": "Lista de {producto_id, cantidad}", "required": True}]),
    "validar_totales": _t("validar_totales",
        "Valida los totales de una venta",
        "validacion", "/api/ventas/validar-totales", "GET",
        [{"name": "subtotal", "type": "float", "description": "Subtotal", "required": True},
         {"name": "descuento", "type": "float", "description": "Descuento", "required": True},
         {"name": "total", "type": "float", "description": "Total", "required": True}]),
    "cierre_calcular": _t("cierre_calcular",
        "Calcula los datos del cierre de caja",
        "validacion", "/api/ventas/cierre-calcular", "GET", []),
    "generar_id": _t("generar_id",
        "Genera un ID unico para venta u otro registro",
        "validacion", "/api/ventas/generar-id", "GET", []),
    "cifrar": _t("cifrar",
        "Cifra un texto con AES",
        "validacion", "/api/util/cifrar", "GET",
        [{"name": "texto", "type": "str", "description": "Texto a cifrar", "required": True}]),
    "descifrar": _t("descifrar",
        "Descifra un texto cifrado con AES",
        "validacion", "/api/util/descifrar", "GET",
        [{"name": "texto_cifrado", "type": "str", "description": "Texto cifrado", "required": True}]),
    "sanitize": _t("sanitize",
        "Sanitiza un texto eliminando caracteres peligrosos",
        "validacion", "/api/util/sanitize", "GET",
        [{"name": "texto", "type": "str", "description": "Texto a sanitizar", "required": True}]),
    "sqli_check": _t("sqli_check",
        "Verifica si un texto contiene patrones de inyeccion SQL",
        "validacion", "/api/util/sqli-check", "GET",
        [{"name": "texto", "type": "str", "description": "Texto a verificar", "required": True}]),
}
