from tools.base import _t

VENTA_TOOLS = {
    "reporte_ventas": _t("reporte_ventas",
        "Reporte de ventas con filtros por fecha, metodo y estado",
        "ventas", "/api/reportes/ventas", "GET",
        [{"name": "fecha_inicio", "type": "str", "description": "Fecha inicio YYYY-MM-DD", "required": False},
         {"name": "fecha_fin", "type": "str", "description": "Fecha fin YYYY-MM-DD", "required": False},
         {"name": "metodo_pago", "type": "str", "description": "Filtrar por metodo de pago", "required": False}]),
    "resumen": _t("resumen",
        "Resumen general del negocio: ventas, gastos, ganancias",
        "ventas", "/api/reportes/resumen", "GET",
        [{"name": "dias", "type": "int", "description": "Periodo en dias", "required": False}]),
    "ganancias": _t("ganancias",
        "Reporte de ganancias detallado por periodo",
        "ventas", "/api/reportes/ganancias", "GET",
        [{"name": "fecha_inicio", "type": "str", "description": "Fecha inicio", "required": False},
         {"name": "fecha_fin", "type": "str", "description": "Fecha fin", "required": False}]),
    "historial_diario": _t("historial_diario",
        "Historial de ventas por dia",
        "ventas", "/api/historial/diario", "GET",
        [{"name": "dias", "type": "int", "description": "Dias a consultar", "required": False}]),
    "historial_detalle": _t("historial_detalle",
        "Detalle de ventas de una fecha especifica",
        "ventas", "/api/historial/diario/<fecha>", "GET",
        [{"name": "fecha", "type": "str", "description": "Fecha YYYY-MM-DD", "required": True}]),
    "listar_gastos": _t("listar_gastos",
        "Lista todos los gastos registrados",
        "ventas", "/api/gastos", "GET",
        [{"name": "fecha_inicio", "type": "str", "description": "Fecha inicio", "required": False},
         {"name": "fecha_fin", "type": "str", "description": "Fecha fin", "required": False}]),
    "crear_gasto": _t("crear_gasto",
        "Registra un nuevo gasto",
        "ventas", "/api/gastos", "POST",
        [{"name": "descripcion", "type": "str", "description": "Descripcion del gasto", "required": True},
         {"name": "monto", "type": "float", "description": "Monto del gasto", "required": True},
         {"name": "categoria", "type": "str", "description": "Categoria del gasto", "required": False}],
        role="vendedor"),
    "eliminar_gasto": _t("eliminar_gasto",
        "Elimina un gasto registrado",
        "ventas", "/api/gastos/<gasto_id>", "DELETE",
        [{"name": "gasto_id", "type": "str", "description": "ID del gasto", "required": True}],
        role="administrador"),
    "listar_descuentos": _t("listar_descuentos",
        "Lista todos los descuentos activos",
        "ventas", "/api/descuentos", "GET", []),
    "crear_descuento": _t("crear_descuento",
        "Crea un nuevo descuento",
        "ventas", "/api/descuentos", "POST",
        [{"name": "nombre", "type": "str", "description": "Nombre del descuento", "required": True},
         {"name": "porcentaje", "type": "float", "description": "Porcentaje de descuento", "required": True},
         {"name": "activo", "type": "bool", "description": "Si esta activo", "required": False}],
        role="administrador"),
    "eliminar_descuento": _t("eliminar_descuento",
        "Elimina un descuento",
        "ventas", "/api/descuentos/<int:did>", "DELETE",
        [{"name": "did", "type": "int", "description": "ID del descuento", "required": True}],
        role="administrador"),
}
